### ISSUE TITLE
Get plain `except`s out of the code base

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/SmokeDetector#2364] opened 2018-08-04 05:06 UTC
I updated [flake8 to 3.5.0][3] some time ago and had to add E722 (bare `except:`) to ignore list at that time. As has been pointed out ([1][1], [2][2]), it's time we remove E722 and enforce it.

  [1]: https://chat.stackexchange.com/transcript/message/45999680#45999680
  [2]: https://chat.stackexchange.com/transcript/message/45999684#45999684
  [3]: https://github.com/Charcoal-SE/SmokeDetector/commit/36e4d1a4e43704b06fd7041ab97e6d537a89b319

**Comment by ArtOfCode-** [comment] 2018-08-04 11:13
Duplicate of #1168

**Closed by ArtOfCode-** 2018-08-04 11:13 UTC
