### ISSUE TITLE
Add a global website whitelist

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/SmokeDetector#532] opened 2017-02-20 01:01 UTC
For example, `example.*` domains are *unlikely* to be used for spam. This feature would allow for filters like “Link at end of answer” to be ignored when a harmless website ends up at the end of the post.

[context](https://chat.stackexchange.com/transcript/message/35543033#35543033)

**Comment by teward** [comment] 2017-02-20 16:42
This *may* be a duplicate of https://github.com/Charcoal-SE/SmokeDetector/issues/490

**Closed** 2017-02-20 16:44 UTC
Labels: duplicate, feature request, spam checks
