### ISSUE TITLE
Registering a question as fp doesn't seem to remove user from blacklist

### ISSUE THREAD

**Issue by CalvT** [Charcoal-SE/SmokeDetector#833] opened 2017-06-14 00:23 UTC
As per ArtofCode:

> fpu- is fp and whitelist user, not remove from blacklist
> just fp- will remove from blacklist

But when I tested that [here](https://chat.stackexchange.com/transcript/message/38095302#38095302) it didn't seem to of have removed me from the blacklist

**Comment by CalvT** [comment] 2017-06-14 00:32
Ok, so the issue is that if the feedback is via Metasmoke, Smokey doesn't unblacklist.

[Tested Here](https://chat.stackexchange.com/transcript/message/38095514#38095514)

**Comment by ArtOfCode-** [comment] 2017-08-16 23:18
Has this been fixed, or is it still a thing?

**Comment by CalvT** [comment] 2017-08-17 10:11
Still a thing - tested it this morning. [Charcoal Record Starts Here](https://chat.stackexchange.com/transcript/message/39460603#39460603)

**Comment by angussidney** [comment] 2017-09-09 10:25
Closing as dupe of #1072, rather than the other way around, because it has more concise info

**Closed by angussidney** 2017-09-09 10:25 UTC
Labels: bug, duplicate
