### ISSUE TITLE
MRR (Massive Regex Refactorization)

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/SmokeDetector#872] opened 2017-06-22 07:09 UTC
[`findspam.py`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py) contains regexes which are used multiple times in identical or very similar ways. This causes problems when maintaining those regexes; one has to do that in several places, if one even *knows* there's a second or third similar regex.

Candidates for refactoring (please add more if you know of them):

#### Link at end (of body, of answer)
https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L85
https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L815 

#### Shortened URL (near end of question, in answer)
https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L844
https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L851

**Comment by AWegnerGitHub** [comment] 2017-06-30 03:26
The following appear related at this point:

- #888 
- #889 
- #890 
- #897 
- #898 
- #899 
- #900
- #901 
- #902
- #904

**Comment by doppeldeveloper** [comment] 2017-06-30 13:07
Related to this, I'm concerned why we have `bad_keywords_nwb` in [findspam.py line 507](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L507) -- it seems to be a duplicate of [`bad_keywords.txt`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/bad_keywords.txt). For example, `bad_keywords` [matches writing services](https://github.com/Charcoal-SE/SmokeDetector/blob/master/bad_keywords.txt#L7) but [so does `bad_keywords_nwb`](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L528).

**Comment by AWegnerGitHub** [comment] 2017-06-30 13:11
It's entirely possible that the duplicates in `find_spam.py` were missed when records were broken out to `bad_keywords.txt`.

**Comment by angussidney** [comment] 2017-07-01 02:55
Yeah. Bad keywords NWB stands for non-word-breaking, which means that it doesn't require there to be a word break either side of the keyword (e.g. In a URL)

**Closed** 2017-08-16 23:07 UTC
Labels: feature request, spam checks
