### ISSUE TITLE
Why isn't my SmokeDetector instance communicating in chat?

### ISSUE THREAD

**Issue by Victor-VosMottor** [Charcoal-SE/SmokeDetector#5084] opened 2020-10-23 09:37 UTC
It is seeing all the commands I type to the chat but doesn't reply to them, why?
Logs:
```
vos-mottor@vosmottor-H370M-DS3H:~/SmokeDetector/SmokeDetector$ python3 nocrash.py
2020-10-23 09:35:35,942:INFO:[NoCrash] Starting with persistent_arguments ['nocrash.py']
[09:35:36.515] Global blacklists loaded
[09:35:36.517] metasmoke host not found. Set it as metasmoke_host in the config file. See https://github.com/Charcoal-SE/metasmoke.
[09:35:36.517] No metasmoke key found, which is okay if both are running on the same host
[09:35:36.517] No metasmoke websocket host found, which is okay if you're anti-websocket
[09:35:37.107] ChatExchange username loaded from config
[09:35:37.107] ChatExchange password loaded from config
[09:35:38.313] chat.stackexchange.com: Login error LoginError: login with cookie could not be verified, try credential login instead
[09:35:38.313] chat.stackexchange.com: Falling back to credential-based login
[09:35:40.217] chat.stackoverflow.com: Login error LoginError: login with cookie could not be verified, try credential login instead
[09:35:40.217] chat.stackoverflow.com: Falling back to credential-based login
[09:35:42.029] chat.meta.stackexchange.com: Login error LoginError: login with cookie could not be verified, try credential login instead
[09:35:42.029] chat.meta.stackexchange.com: Falling back to credential-based login
[09:35:45.857] VosMottor/Smokey active
[09:35:45.857] MS host: None
[09:35:50.774] New IDs / Hybrid Intermediate IDs for math.stackexchange.com:
[09:35:50.775] [3877836]
[09:35:50.775] [ *Identical* ]
[09:35:51.044] New IDs / Hybrid Intermediate IDs for ux.stackexchange.com:
[09:35:51.044] [135160]
[09:35:51.044] [ *Identical* ]
[09:35:51.311] New IDs / Hybrid Intermediate IDs for astronomy.stackexchange.com:
[09:35:51.311] [7863]
[09:35:51.311] [ *Identical* ]
[09:35:54.217] Command received: !!/alive
[09:35:55.376] Returning cached links for post
```
config:
```
[Config]
location=VosMottor/Smokey

ChatExchangeU=smokedetector.of.vos@rambler.ru
ChatExchangeP=<valid_password>
```
rooms.yml:
```
stackexchange.com:
  115386:
    commands: true

    msg_types:
      - debug
      - metasmoke
      - all-sites
      - experimental-all-sites
      - no-offensive-mask
```

**Comment by tripleee** [comment] 2020-10-23 09:38
I'm guessing your user does not have enough rep to participate in chat.

**Comment by tripleee** [comment] 2020-10-23 09:39
(Closing as not a bug; feel free to reopen if my diagnosis was incorrect.)

**Comment by Victor-VosMottor** [comment] 2020-10-23 09:39
Nope it has 23 rep i earned yesterday for it.

**Comment by Victor-VosMottor** [comment] 2020-10-23 09:39
How to reopen?

**Closed by tripleee** 2020-10-23 09:39 UTC

**Comment by Victor-VosMottor** [comment] 2020-10-23 09:47
A-a-a-aHHHH! I created locked room and doesn't provided access. Yep, should be close.
