### ISSUE TITLE
Make notification (ping) preferences global across all instances

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/SmokeDetector#2828] opened 2019-04-02 03:37 UTC
Regarding https://stackoverflow.com/c/charcoal/questions/530 (only visible to Charcoal SO Team members):

When requesting that SmokeDetector ping one for posts it reports on a specific site using the `!!/notify` command, that preference is set only on the instance that happens to be doing duty at that time. If we start running a different instance (or if the owner of an instance needs to reinstall SmokeDetector on their instance), said preference is effectively cleared, and must be set on that instance again.

Similarly, if someone who is currently being pinged for posts on a specific site (and has that setting set on multiple instances, per above), if the user decides they no longer want to be pinged, their command will only disable it on that specific instance, so if another instance with the old ping preference is activated, they will once again be pinged despite previously asking the bot to stop pinging them.

Can we please store user notification preferences globally, rather than locally on each instance? Saving them on a database of some sort (or a file here on GitHub) seems like a better solution because instances can just query it to see who's globally opted in or out of notifications. It also has the added benefit that in case an instance owner needs to clear all data and reinstall SmokeDetector, ping preferences would no longer be cleared.

**Comment by ArtOfCode-** [comment] 2019-04-02 06:22
Duplicate of #1281

**Closed by ArtOfCode-** 2019-04-02 06:22 UTC

**Comment by gparyani** [comment] 2019-04-02 16:12
@ArtOfCode- Until Helios is ready, is there a stopgap solution that can be implemented (e.g. by using a file on this repository), while Helios is still being worked on?

**Comment by ArtOfCode-** [comment] 2019-04-03 14:56
@gparyani there probably _is_, it's just a question of cost/benefit, which... doesn't come out in favour
