### ISSUE TITLE
"English text on localized site" should ignore HTML tags

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/SmokeDetector#3844] opened 2020-05-13 09:09 UTC
### What problem has occurred? What issues has it caused?

Magnificent demo: https://m.erwaysoftware.com/posts/uid/rus/460730

The post is in Russian but it used code formatting which was replaced with English text internally.

### What would you like to happen/not happen?

Don't examine code blocks for this rule?

**Comment by makyen** [comment] 2020-05-16 16:22
Note: This detection already ignores code blocks. What appears to be the issue is that the detection caught the HTML tags, not the code. I've edited the title of this issue to reflect that.

**Comment by gparyani** [comment] 2020-06-17 02:59
Duplicate of #2640 (@makyen)

**Closed** 2020-06-17 03:15 UTC
Labels: type: duplicate
